#!/bin/bash

make clean
make
sudo rmmod inputstat.ko
/usr/src/linux-headers-6.2.0-39-generic/scripts/sign-file sha256     ~/signing_key.priv     ~/signing_key.x509     ./inputstat.ko
sudo insmod inputstat.ko
